export const platformsList = [
  "PC",
  "PlayStation 4",
  "PlayStation 5",
  "Xbox One",
  "Xbox Series X/S",
  "Nintendo Switch",
  "Mobile",
  "PlayStation 3",
  "Xbox 360",
  "Wii U",
  "Nintendo 3DS",
  "PlayStation Vita",
  "Google Stadia",
  "Amazon Luna",
  "Oculus Quest",
  "HTC Vive",
  "Nintendo Wii",
  "Sega Dreamcast",
  "PlayStation 2",
  "Xbox",
];